#!/bin/bash
CONFIG_TEMPLATE="${TRIM_APPDEST}/template/aria2.tpl"
CONFIG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/data/aria2.conf"

sed \
  -e "s|\${PRC_SECRET}|$rpc_secret|g" \
  "$CONFIG_TEMPLATE" > "$CONFIG_FILE"

exit 0