#!/bin/bash
LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/logs/read.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"
READ_JAR="${TRIM_DATA_SHARE_PATHS%%:*}/read.jar"
WORK_DIR="${TRIM_DATA_SHARE_PATHS%%:*}"
UI_PORT="$ui_port"
PROXY_MODE="$proxypng"
PROXY_IP="$proxy_ip"
PROXY_PORT="$proxy_port"
RUN_MODE="$run_mode"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

get_java_cmd() {
    if [ -x "/var/apps/java-25-openj9/target/bin/java" ]; then
        echo "/var/apps/java-25-openj9/target/bin/java"
        return
    fi
    
    if [ -x "/var/apps/java-25-openjdk/target/bin/java" ]; then
        echo "/var/apps/java-25-openjdk/target/bin/java"
        return
    fi
    
    echo ""
}

start_process() {
    if status; then
        return 0
    fi

    JAVA_CMD=$(get_java_cmd)
    if [ -z "$JAVA_CMD" ]; then
        echo "未找到Java! 先安装java-25-openj9或java-25-openjdk" > ${TRIM_TEMP_LOGFILE}
        return 1
    fi

    log_msg "Java: ${JAVA_CMD}"
    #---构建启动参数---
    if [ "${RUN_MODE}" = "low" ]; then
        JAVA_OPTS="-Xms128m -Xmx512m"
        log_msg "单用户模式"
    else
        JAVA_OPTS="-Xms512m -Xmx2g"
        log_msg "多用户模式"
    fi
    # 图片代理模式
    if [ "${PROXY_MODE}" = "true" ]; then       
        JAVA_OPTS="${JAVA_OPTS} -Dhttp.proxyHost=${PROXY_IP} -Dhttp.proxyPort=${PROXY_PORT}"
        JAVA_OPTS="${JAVA_OPTS} -Dhttps.proxyHost=${PROXY_IP} -Dhttps.proxyPort=${PROXY_PORT}"
        log_msg "启动图片代理"
    else
        log_msg "未启动图片代理"
    fi
    # 设置字符编码，解决中文文件名问题
    JAVA_OPTS="${JAVA_OPTS} -Dfile.encoding=UTF-8"
    JAVA_OPTS="${JAVA_OPTS} -Dsun.jnu.encoding=UTF-8"
    JAVA_OPTS="${JAVA_OPTS} -Dsun.stdout.encoding=UTF-8"
    JAVA_OPTS="${JAVA_OPTS} -Dsun.stderr.encoding=UTF-8"
    # web端口
    JAVA_OPTS="${JAVA_OPTS} -Dserver.port=$UI_PORT"
    CMD="${JAVA_CMD} ${JAVA_OPTS} -jar ${READ_JAR}"
    log_msg "CMD = ${CMD}"
    log_msg "Starting process ..."
    # run cmd to start process
    cd ${WORK_DIR}
    nohup ${CMD} 2>&1 &
    # write pid to pidfile
    printf "%s" "$!" > ${PID_FILE}
    # log_msg "CMD = ${CMD}"
    # log_msg "pid = $!"
    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        
        log_msg "pid=${pid}"
        if ! check_process "${pid}"; then
            # process not exist, delete pidfile
            rm -f "${PID_FILE}"
            log_msg "remove pid file 1"
            return
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "process killed... "
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac