#已为飞牛os特化构建，谨慎修改
worker_processes  auto;

error_log  /var/apps/Nginx/shares/logs/error.log notice;  #注意路径
pid        /var/apps/Nginx/var/nginx.pid;                 #注意路径

events {
    worker_connections  1024;
}

http {
    include       /var/apps/Nginx/shares/etc/mime.types;  #注意路径
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/apps/Nginx/shares/logs/access.log  main; #注意路径

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /var/apps/Nginx/shares/etc/conf.d/*.conf;
    include /var/apps/Nginx/shares/etc/sites-enabled/*;      #nginx-ui站点目录
}

stream {
	include /var/apps/Nginx/shares/etc/streams-enabled/*;      #nginx-ui上游目录
}
