#!/bin/bash
export PATH=/var/apps/nodejs_v24/target/bin:$PATH
export PORT=$ui_port
export REDIS_URL=redis://localhost:6379
export ADMIN_PASSWORD=$admin_password
HTTPS_PROXY=$https_proxy
if [ "$proxy_switch" = "on" ]; then
    export https_proxy=$HTTPS_PROXY
else
    unset https_proxy
fi

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"


log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    # run cmd to start process
    nohup node ${TRIM_APPDEST}/src/app.js >> ${LOG_FILE} 2>&1 &
    # write pid to pidfile
    printf "%s" "$!" > ${PID_FILE}
    # log_msg "CMD = ${CMD}"
    # log_msg "pid = $!"
    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    pkill -TERM -u MoveCar -x "MainThread"

    while pgrep -u MoveCar -x "MainThread" > /dev/null; do
        if pgrep -u MoveCar -x "MainThread" > /dev/null; then
            log_msg "进程 'MainThread' 仍在运行，等待中..."
        fi
        sleep 1
    done

    # 清理 PID 文件
    if [ -f "${PID_FILE}" ]; then
        rm -f "${PID_FILE}"
        log_msg "已删除 PID 文件: ${PID_FILE}"
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac