name: Extract OpenJDK

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        # 只保留版本标签，公共前缀在下面定义
        tag: [open-25-jre-noble, open-21-jre-noble, open-17-jre-noble, open-11-jre-noble, open-8-jre-noble]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Files
        run: |
          # 定义公共镜像仓库前缀
          REGISTRY="ibm-semeru-runtimes"
          IMAGE="${REGISTRY}:${{ matrix.tag }}"
          
          docker pull $IMAGE
          docker run --rm -v ${{ github.workspace }}:/host $IMAGE cp -r /opt/java/openjdk /host/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # 使用 tag 变量来命名，保持清晰
          name: openjdk-${{ matrix.tag }}-${{ matrix.os }}
          path: openjdk
          retention-days: 5
