name: Extract OpenJDK

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        image: [ibm-semeru-runtimes:open-25-jre-noble, ibm-semeru-runtimes:open-21-jre-noble,ibm-semeru-runtimes:open-17-jre-noble,ibm-semeru-runtimes:open-11-jre-noble,ibm-semeru-runtimes:open-8-jre-noble]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Files
        run: |
          # 拉取镜像
          docker pull ${{ matrix.image }}
          
          # 直接提取 /opt/java/openjdk 到当前目录
          # 这样提取出来的文件夹名就是 openjdk
          docker run --rm -v ${{ github.workspace }}:/host ${{ matrix.image }} cp -r /opt/java/openjdk /host/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openjdk-${{ matrix.image }}-${{ matrix.os }}
          path: openjdk
          retention-days: 5
